# Weather API Configuration

# OpenWeatherMap API settings
openweathermap:
  base_url: "https://api.openweathermap.org/data/2.5"
  api_key: "YOUR_API_KEY_HERE"  # Replace with your actual API key
  endpoints:
    current: "/weather"
    forecast: "/forecast"
  parameters:
    units: "metric"  # celsius for temperature
    lang: "en"       # response language

# API request settings
request:
  timeout: 30  # seconds
  retry_attempts: 3
  retry_delay: 5    # seconds between retries

# Location settings
default_locations:
  - name: "New York"
    country: "US"
    lat: 40.7128
    lon: -74.0060
  - name: "London"
    country: "GB"
    lat: 51.5074
    lon: -0.1278

# Data collection settings
collection:
  frequency: "hourly"    # how often to collect data
  batch_size: 100       # number of records to process at once
  max_requests_per_day: 1000
